# Site wide configuration

title: "MechanAir"
description: "National HVAC, Mechanical, Plumbing service provider for commercial clients"
logo: images/logo.png
teaser: 
locale: en
url: https://mechanair.com
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 5

collections:
  services:
    output: true
  companies:
    output: true
  careers:
    output: true 
  tag:
    output: true   

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "services"  
  - scope:
      path: ""
      type: "careers"
    values:
      layout: "career-listing"    
  - scope:
      path: ""
      type: "companies"
    values:
      layout: "companies" 
  - scope:
      path: ""
      type: "tag"
    values:
      layout: "tag"                     

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
